### ISSUE TITLE
Refactoring - tracking

### ISSUE THREAD

**Issue by tz70s** [allenlee820202/nexcom-project#1]
We need to deal with these jobs for refactoring.

- [x] Clean-up
  - [x] Remove unused folders, files
  - [x] Remove unused code
- [x] Restructure
  - [x] More verbose file name
- [x] Code's maintenance #17 
  - [x] Add comments
  - [x] Format style
  - [x] Naming style
  - [x] Document
- [x] Modify relative path #12
- [x] Tests #11 
- [x] Add scripts #10 
  - [x] Daemonized database
  - [x] Daemonized backend server

**Comment by allenlee820202** [comment]
Should the path structure look like this?
/backend
      index.js
      /route
/frontend
      /html
      /js
      /css

**Comment by tz70s** [comment]
Done for the first big refactoring! But leave the test issue remain.
